In [1]:
from nltk.corpus import movie_reviews

In [2]:
movie_reviews.categories()

['neg', 'pos']

In [3]:
movie_reviews.fileids('neg')

['neg/cv000_29416.txt',
 'neg/cv001_19502.txt',
 'neg/cv002_17424.txt',
 'neg/cv003_12683.txt',
 'neg/cv004_12641.txt',
 'neg/cv005_29357.txt',
 'neg/cv006_17022.txt',
 'neg/cv007_4992.txt',
 'neg/cv008_29326.txt',
 'neg/cv009_29417.txt',
 'neg/cv010_29063.txt',
 'neg/cv011_13044.txt',
 'neg/cv012_29411.txt',
 'neg/cv013_10494.txt',
 'neg/cv014_15600.txt',
 'neg/cv015_29356.txt',
 'neg/cv016_4348.txt',
 'neg/cv017_23487.txt',
 'neg/cv018_21672.txt',
 'neg/cv019_16117.txt',
 'neg/cv020_9234.txt',
 'neg/cv021_17313.txt',
 'neg/cv022_14227.txt',
 'neg/cv023_13847.txt',
 'neg/cv024_7033.txt',
 'neg/cv025_29825.txt',
 'neg/cv026_29229.txt',
 'neg/cv027_26270.txt',
 'neg/cv028_26964.txt',
 'neg/cv029_19943.txt',
 'neg/cv030_22893.txt',
 'neg/cv031_19540.txt',
 'neg/cv032_23718.txt',
 'neg/cv033_25680.txt',
 'neg/cv034_29446.txt',
 'neg/cv035_3343.txt',
 'neg/cv036_18385.txt',
 'neg/cv037_19798.txt',
 'neg/cv038_9781.txt',
 'neg/cv039_5963.txt',
 'neg/cv040_8829.txt',
 'neg/cv041_22364.txt',


In [4]:
movie_reviews.words(movie_reviews.fileids()[5])

['capsule', ':', 'in', '2176', 'on', 'the', 'planet', ...]

In [5]:
document =[]
for category in movie_reviews.categories():
    for fileid in movie_reviews.fileids(category):
        document.append((movie_reviews.words(fileid) , category))
document[0:5]

[(['plot', ':', 'two', 'teen', 'couples', 'go', 'to', ...], 'neg'),
 (['the', 'happy', 'bastard', "'", 's', 'quick', 'movie', ...], 'neg'),
 (['it', 'is', 'movies', 'like', 'these', 'that', 'make', ...], 'neg'),
 (['"', 'quest', 'for', 'camelot', '"', 'is', 'warner', ...], 'neg'),
 (['synopsis', ':', 'a', 'mentally', 'unstable', 'man', ...], 'neg')]

In [6]:
import random 
random.shuffle(document)
document[0:5]

[(['nosferatu', 'the', 'vampyre', '(', 'germany', '1979', ...], 'pos'),
 (['ultra', 'low', 'budget', 'but', 'extremely', ...], 'pos'),
 (['bob', 'the', 'happy', 'bastard', "'", 's', 'quickie', ...], 'pos'),
 (['i', 'guess', 'there', 'are', 'those', 'who', 'have', ...], 'pos'),
 (['summary', 'five', 'liberal', 'iowa', 'graduate', ...], 'pos')]

In [7]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [8]:
from nltk.corpus import wordnet
def get_simple_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [9]:
from nltk.corpus import stopwords
import string
stops = set(stopwords.words('english'))
punctuations = list(string.punctuation)
stops.update(punctuations)


In [10]:
from nltk import pos_tag
def clean_review(words):
    output_words=[]
    for w in  words:
        if w.lower() not in stops:
            pos = pos_tag([w])
            clean_word =lemmatizer.lemmatize(w,pos = get_simple_pos(pos[0][1]))
            output_words.append(clean_word.lower())
    return output_words

In [11]:
documents = [ (clean_review(document) , category) for document,category in document]

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
train_set = {"the sky sky is blue " , "the sun is bright"}
count_vec = CountVectorizer(max_features =3)
a = count_vec.fit_transform(train_set)
a.todense()

matrix([[1, 0, 1],
        [1, 2, 1]], dtype=int64)

In [34]:
count_vec.get_feature_names_out()

array(['is', 'sky', 'the'], dtype=object)

In [35]:
categories = [category for document , category in documents]

In [36]:
text_document =[''.join(document) for document,category in documents]

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train ,x_test ,y_train , y_test = train_test_split(text_document, categories)

In [80]:
count_vec = CountVectorizer(max_features = 2000)
x_train_features = count_vec.fit_transform(x_train)
x_train_features.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
count_vec.get_feature_names_out()

array(['1000foottidalwaveenddeepimpactsayprettyaccuratelyrepresenttowerfloodlasttwoyearworthdisastermoviegetirwinallenesqueeveryreleaseearlywaverevivalcheesylaughableleastknewincludethrilleveryfivetenminutedeepimpacttrydisguisehumandramaendlessfillercomprisedisasterpreventionplancountrykeeptakerepeatcyclefollow',
       '137',
       '2sequelmissionimpossiblejamesbondwannabefilmfailsevencomeclosefilmwithumorentertainmentvaluetryspyromancemoviewithoutsuspensefilmlooklikeextendcommercialdudethinklookcoolthrowawaysunglassfilmpreferstechiegadgetanythinghumancoolestthingmovieholestorytritethingmovieusagedovethroughoutpeacesymbolfilmplaywetfantasydreamtechieviolenceexceptchoreographedactionsequencefilmdullthreequartertimefillmanydeadspotstorygarnerconcernwoodencharactersuperficialromancedevelopedactionscenemightlookgoodconvertviolencefilmadvertisementsadisticresponsenothingshortmindlesscartoonviolencemakedifficultsitbackapplaudwithoutfeelputgratuitouscrueltysee2openclosefastpaceactionsceneha

In [47]:
x_test_feature=count_vec.transform(x_test)

In [48]:
x_test_feature

<500x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [49]:
from sklearn.svm import SVC

In [64]:
svc = SVC()

In [67]:
svc.fit(x_train_features ,y_train)

SVC()

In [54]:
svc.score(x_test_feature,y_test)

0.538

In [78]:
count_vec = CountVectorizer(max_features = 2000 , ngram_range = (2,3))
x_train_features = count_vec.fit_transform(x_train)
x_train_features.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [71]:
for i in count_vec.get_feature_names_out():
    print(i)
    print()

1000foottidalwaveenddeepimpactsayprettyaccuratelyrepresenttowerfloodlasttwoyearworthdisastermoviegetirwinallenesqueeveryreleaseearlywaverevivalcheesylaughableleastknewincludethrilleveryfivetenminutedeepimpacttrydisguisehumandramaendlessfillercomprisedisasterpreventionplancountrykeeptakerepeatcyclefollow presidentmorganfreemangotvtellcountryremotechancecometstrikeearthnationcrackscientistastronautbrilliantplanstopproblemgetseeplanactionsequenceutterlylacksuspensemissionbarelyfailfreemantellcountrycometstillheadtowardearthremotechancestrikenationcrackscientistastronautbrilliantplanstopproblemgothroughoutmovieeverytimefreemangotvknowplangofailknowseetvaddeepimpactadfeaturefreemantellnationcometstillheadrightushowdisastershotcometstrikeearthgianttidalwavespreadladygentlemanmoviesuccessfuldisastermoviemaindisastertowardbeginlittledisasterfollowdeepimpactsaveonedisasterenddiscloses30secondtvspottelevisionwrongdeepimpactmaincharacterplayedtealeonilowlevelbroadcastjournalistmsnbcmeretipproduct

In [72]:
x_test_feature=count_vec.transform(x_test)

In [73]:
svc = SVC()

In [74]:
svc.fit(x_train_features ,y_train)

SVC()

In [75]:
svc.score(x_test_feature,y_test)

0.538